package codegen

import (
	"fmt"
	"testing"

	"github.com/grafana/codejen"
	"github.com/stretchr/testify/require"
)

func TestPrefixer(t *testing.T) {
	req := require.New(t)
	fileContent := []byte("with content")
	inputFile := codejen.NewFile("some.file", fileContent)

	resultFile, err := Prefixer("/the/prefix")(*inputFile)
	req.NoError(err)

	req.Equal("/the/prefix/some.file", resultFile.RelativePath)
	req.Equal(fileContent, resultFile.Data)
}

func TestSlashHeaderMapper(t *testing.T) {
	markdownContent := `# A document title

With some content`

	jsonContent := `{
  "status": "all green"
}`

	yamlContent := `status: "all green"`
	expectedYamlContent := fmt.Sprintf(`# Code generated - EDITING IS FUTILE. DO NOT EDIT.
#
# Generated by:
#     generator name
# Using jennies:
#
# Run 'make gen-cue' from repository root to regenerate.

%s`, yamlContent)

	goContent := `type SomeType struct {
	Foo string
}`
	expectedGoContent := fmt.Sprintf(`// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     generator name
// Using jennies:
//
// Run 'make gen-cue' from repository root to regenerate.

%s`, goContent)

	tsContent := `export interface SomeType {
	foo: string;
}`
	expectedTsContent := fmt.Sprintf(`// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     generator name
// Using jennies:
//
// Run 'make gen-cue' from repository root to regenerate.

%s`, tsContent)

	testCases := []struct {
		name            string
		inputFile       *codejen.File
		expectedContent string
	}{
		{
			name:            "markdown file",
			inputFile:       codejen.NewFile("./dir/README.md", []byte(markdownContent)),
			expectedContent: markdownContent,
		},
		{
			name:            "json file",
			inputFile:       codejen.NewFile("./dir/data.json", []byte(jsonContent)),
			expectedContent: jsonContent,
		},
		{
			name:            "yaml file",
			inputFile:       codejen.NewFile("./dir/data.yaml", []byte(yamlContent)),
			expectedContent: expectedYamlContent,
		},
		{
			name:            "yml file",
			inputFile:       codejen.NewFile("./dir/data.yml", []byte(yamlContent)),
			expectedContent: expectedYamlContent,
		},
		{
			name:            "go file",
			inputFile:       codejen.NewFile("./dir/main.go", []byte(goContent)),
			expectedContent: expectedGoContent,
		},
		{
			name:            "ts type",
			inputFile:       codejen.NewFile("./dir/main.ts", []byte(tsContent)),
			expectedContent: expectedTsContent,
		},
	}

	for _, testCase := range testCases {
		tc := testCase

		t.Run(tc.name, func(t *testing.T) {
			req := require.New(t)

			resultFile, err := SlashHeaderMapper("generator name")(*tc.inputFile)
			req.NoError(err)

			req.Equal(tc.expectedContent, string(resultFile.Data))
		})
	}
}
